version: '3.8'

services:
  web:
    container_name: web
    build: ./ristorante
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/ristorante
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:admin@db:5432/ristorante
      RAILS_MASTER_KEY: e4dec0874f2625aba3e070d996e82751
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ristorante
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
