default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  pool: 5

development:
  <<: *default
  database: ristorante

production:
  <<: *default
  database: ristorante

